jaffle_shop:
  outputs:
    dev:
      type: postgres
      threads: 1
      host: postgresql.postgresql.svc.cluster.local
      port: 5432
      user: postgres
      pass: admin
      dbname: postgres
      schema: public
  target: dev
